### ISSUE TITLE
how run?

### ISSUE THREAD

**Issue by mousesport** [Crahl/nodejs_p2pool_scanner#1]
nodejs server.js

> module.js:340
>     throw err;
>           ^
> Error: Cannot find module 'express'
>     at Function.Module._resolveFilename (module.js:338:15)
>     at Function.Module._load (module.js:280:25)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/home/mousesport/p2pool-new/nodejs_p2pool_scanner/server.js:3:12)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Function.Module.runMain (module.js:497:10)

nodejs server.js

> module.js:340
>     throw err;
>           ^
> Error: Cannot find module 'socket.io'
>     at Function.Module._resolveFilename (module.js:338:15)
>     at Function.Module._load (module.js:280:25)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/home/mousesport/p2pool-new/nodejs_p2pool_scanner/server.js:5:11)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Function.Module.runMain (module.js:497:10)

`
npm install socket.io

> npm http GET https://registry.npmjs.org/socket.io
> npm http 304 https://registry.npmjs.org/socket.io
> npm http GET https://registry.npmjs.org/engine.io/1.5.4
> npm http GET https://registry.npmjs.org/has-binary-data/0.1.3
> npm http GET https://registry.npmjs.org/socket.io-client/1.3.7
> npm http GET https://registry.npmjs.org/socket.io-adapter/0.3.1
> npm http GET https://registry.npmjs.org/socket.io-parser/2.2.4
> npm http GET https://registry.npmjs.org/debug/2.1.0
> npm http 304 https://registry.npmjs.org/socket.io-parser/2.2.4
> npm http 304 https://registry.npmjs.org/has-binary-data/0.1.3
> npm http 304 https://registry.npmjs.org/socket.io-client/1.3.7
> npm http 304 https://registry.npmjs.org/engine.io/1.5.4
> npm http 304 https://registry.npmjs.org/socket.io-adapter/0.3.1
> npm http 304 https://registry.npmjs.org/debug/2.1.0
> npm http GET https://registry.npmjs.org/debug/1.0.2
> npm http GET https://registry.npmjs.org/object-keys/1.0.1
> npm http GET https://registry.npmjs.org/socket.io-parser/2.2.2
> npm http GET https://registry.npmjs.org/ms/0.6.2
> npm http GET https://registry.npmjs.org/isarray/0.0.1
> npm http GET https://registry.npmjs.org/ws/0.8.0
> npm http GET https://registry.npmjs.org/debug/1.0.3
> npm http GET https://registry.npmjs.org/base64id/0.1.0
> npm http GET https://registry.npmjs.org/engine.io-parser/1.2.2
> npm http GET https://registry.npmjs.org/debug/0.7.4
> npm http GET https://registry.npmjs.org/component-emitter/1.1.2
> npm http GET https://registry.npmjs.org/component-bind/1.0.0
> npm http GET https://registry.npmjs.org/object-component/0.0.3
> npm http GET https://registry.npmjs.org/parseuri/0.0.2
> npm http GET https://registry.npmjs.org/engine.io-client/1.5.4
> npm http GET https://registry.npmjs.org/has-binary/0.1.6
> npm http GET https://registry.npmjs.org/indexof/0.0.1
> npm http GET https://registry.npmjs.org/backo2/1.0.2
> npm http GET https://registry.npmjs.org/to-array/0.1.3
> npm http GET https://registry.npmjs.org/json3/3.2.6
> npm http GET https://registry.npmjs.org/benchmark/1.0.0
> npm http 304 https://registry.npmjs.org/isarray/0.0.1
> npm http 304 https://registry.npmjs.org/object-keys/1.0.1
> npm http 304 https://registry.npmjs.org/debug/1.0.2
> npm http 304 https://registry.npmjs.org/ms/0.6.2
> npm http 304 https://registry.npmjs.org/socket.io-parser/2.2.2
> npm http 304 https://registry.npmjs.org/ws/0.8.0
> npm http 304 https://registry.npmjs.org/debug/1.0.3
> npm http 304 https://registry.npmjs.org/debug/0.7.4
> npm http 304 https://registry.npmjs.org/object-component/0.0.3
> npm http 304 https://registry.npmjs.org/base64id/0.1.0
> npm http 304 https://registry.npmjs.org/engine.io-parser/1.2.2
> npm http 304 https://registry.npmjs.org/component-emitter/1.1.2
> npm http 304 https://registry.npmjs.org/component-bind/1.0.0
> npm http GET https://registry.npmjs.org/after/0.8.1
> npm http GET https://registry.npmjs.org/base64-arraybuffer/0.1.2
> npm http GET https://registry.npmjs.org/blob/0.0.4
> npm http GET https://registry.npmjs.org/utf8/2.1.0
> npm http GET https://registry.npmjs.org/arraybuffer.slice/0.0.6
> npm http GET https://registry.npmjs.org/ultron
> npm http GET https://registry.npmjs.org/utf-8-validate
> npm http GET https://registry.npmjs.org/options
> npm http GET https://registry.npmjs.org/bufferutil
> npm http 304 https://registry.npmjs.org/parseuri/0.0.2
> npm http 304 https://registry.npmjs.org/engine.io-client/1.5.4
> npm http 304 https://registry.npmjs.org/has-binary/0.1.6
> npm http 304 https://registry.npmjs.org/indexof/0.0.1
> npm http 304 https://registry.npmjs.org/backo2/1.0.2
> npm http 304 https://registry.npmjs.org/json3/3.2.6
> npm http 304 https://registry.npmjs.org/after/0.8.1
> npm http 304 https://registry.npmjs.org/to-array/0.1.3
> npm http GET https://registry.npmjs.org/better-assert
> npm http GET https://registry.npmjs.org/debug/1.0.4
> npm http GET https://registry.npmjs.org/parseqs/0.0.2
> npm http GET https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
> npm http 304 https://registry.npmjs.org/benchmark/1.0.0
> npm http GET https://registry.npmjs.org/parseuri/0.0.4
> npm http GET https://registry.npmjs.org/has-cors/1.0.3
> npm http GET https://registry.npmjs.org/component-inherit/0.0.3
> npm http GET https://registry.npmjs.org/parsejson/0.0.1
> npm http 304 https://registry.npmjs.org/base64-arraybuffer/0.1.2
> npm http 304 https://registry.npmjs.org/ultron
> npm http 304 https://registry.npmjs.org/blob/0.0.4
> npm http 304 https://registry.npmjs.org/utf-8-validate
> npm http 304 https://registry.npmjs.org/options
> npm http 304 https://registry.npmjs.org/bufferutil
> npm http 304 https://registry.npmjs.org/better-assert
> npm http 304 https://registry.npmjs.org/utf8/2.1.0
> npm http GET https://registry.npmjs.org/bindings
> npm http GET https://registry.npmjs.org/bindings
> npm http GET https://registry.npmjs.org/callsite/1.0.0
> npm http GET https://registry.npmjs.org/nan
> npm http GET https://registry.npmjs.org/nan
> npm http 304 https://registry.npmjs.org/arraybuffer.slice/0.0.6
> npm http 304 https://registry.npmjs.org/debug/1.0.4
> npm http 304 https://registry.npmjs.org/has-cors/1.0.3
> npm http 304 https://registry.npmjs.org/bindings
> npm http 304 https://registry.npmjs.org/bindings
> npm http 304 https://registry.npmjs.org/parseqs/0.0.2
> npm http 304 https://registry.npmjs.org/parseuri/0.0.4
> npm http 304 https://registry.npmjs.org/parsejson/0.0.1
> npm http 304 https://registry.npmjs.org/nan
> npm http 304 https://registry.npmjs.org/nan
> npm http 304 https://registry.npmjs.org/component-inherit/0.0.3
> 
> > bufferutil@1.2.1 install /home/mousesport/p2pool-new/nodejs_p2pool_scanner/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> > node-gyp rebuild
> 
> 
> > utf-8-validate@1.2.2 install /home/mousesport/p2pool-new/nodejs_p2pool_scanner/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> > node-gyp rebuild
> 
> npm http 304 https://registry.npmjs.org/callsite/1.0.0
> npm http 200 https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
> npm http GET https://github.com/component/global/archive/v2.0.1.tar.gz
> 
> > utf-8-validate@1.2.2 install /home/mousesport/p2pool-new/nodejs_p2pool_scanner/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> > node-gyp rebuild
> 
> 
> > bufferutil@1.2.1 install /home/mousesport/p2pool-new/nodejs_p2pool_scanner/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> > node-gyp rebuild
> 
> /bin/sh: 1: node: not found
> /bin/sh: 1: node: not found
> gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
> gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
> /bin/sh: 1: node: not found
> /bin/sh: 1: node: not found
> gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
> gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
> gyp ERR! configure error 
> gyp ERR! configure error 
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gypgyp gypERR!  stack      at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
> ERR!gyp  ERR! configure error 
> configure errorERR!gyp  
>  ERR!stack      at ChildProcess.EventEmitter.emit (events.js:98:17)
> stackgyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
>  Error: `gyp` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
> gyp ERR!gyp  SystemERR! Linux 3.19.0-25-generic
>  gyp stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
> ERR! commandgyp "nodejs" "/usr/bin/node-gyp" "rebuild"
>  ERR!gyp  stackERR!     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
> gyp gypERR!   stackERR! stackgyp  Error: `gyp` failed with exit code: 1
> ERR!gyp Error: `gyp` failed with exit code: 1
>  ERR! gyp  Systemstack Linux 3.19.0-25-generic
> ERR!     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)                                                                                                                                      
>  stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)                                                                                                                                    
> gyp gyp gyp ERR! ERR!command  "nodejs" "/usr/bin/node-gyp" "rebuild"
> ERR! gypstack      at ChildProcess.EventEmitter.emit (events.js:98:17)
> ERR!gypstack      at ChildProcess.EventEmitter.emit (events.js:98:17)
> ERR! gyp stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
> ERR!  stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
> gyp ERR! gyp cwdERR! /home/mousesport/p2pool-new/nodejs_p2pool_scanner/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
>  System Linux 3.19.0-25-generic
> gyp SystemERR!gyp Linux 3.19.0-25-generic
>   node -v v0.10.25
> ERR! gyp commandgyp "nodejs" "/usr/bin/node-gyp" "rebuild"
>  ERR! ERR! commandgypnode-gyp -v "nodejs" "/usr/bin/node-gyp" "rebuild"
>   v0.10.10
> ERR!gypgyp  ERR!ERR! not ok 
>   cwd /home/mousesport/p2pool-new/nodejs_p2pool_scanner/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> gyp ERR! node -v v0.10.25
> gyp ERR! node-gyp -v v0.10.10
> gyp ERR! not okcwd 
>  /home/mousesport/p2pool-new/nodejs_p2pool_scanner/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> gypcwd  /home/mousesport/p2pool-new/nodejs_p2pool_scanner/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> ERR! node -vgyp v0.10.25
>  ERR!gyp  node -v v0.10.25
> ERR! node-gyp -vnpmgyp v0.10.10
>   ERR!gyp  node-gyp -v v0.10.10
> ERR!WARN not ok 
> gyp  This failure might be due to the use of legacy binary "node"
> ERR! not ok 
> npm WARN For further explanations, please read
> /usr/share/doc/nodejs/README.Debian
>  
> npm WARN This failure might be due to the use of legacy binary "node"
> npm WARN For further explanations, please read
> /usr/share/doc/nodejs/README.Debian
>  
> npm WARN This failure might be due to the use of legacy binary "node"
> npm WARN For further explanations, please read
> /usr/share/doc/nodejs/README.Debian
>  
> npm WARN This failure might be due to the use of legacy binary "node"
> npm WARN For further explanations, please read
> /usr/share/doc/nodejs/README.Debian
>  
> npm WARN optional dep failed, continuing bufferutil@1.2.1
> npm WARN optional dep failed, continuing utf-8-validate@1.2.2
> npm WARN optional dep failed, continuing bufferutil@1.2.1
> npm WARN optional dep failed, continuing utf-8-validate@1.2.2
> npm http 200 https://github.com/component/global/archive/v2.0.1.tar.gz
> socket.io@1.3.7 node_modules/socket.io
> ├── has-binary-data@0.1.3 (isarray@0.0.1)
> ├── debug@2.1.0 (ms@0.6.2)
> ├── socket.io-parser@2.2.4 (isarray@0.0.1, debug@0.7.4, component-emitter@1.1.2, benchmark@1.0.0, json3@3.2.6)
> ├── socket.io-adapter@0.3.1 (object-keys@1.0.1, debug@1.0.2, socket.io-parser@2.2.2)
> ├── engine.io@1.5.4 (base64id@0.1.0, debug@1.0.3, engine.io-parser@1.2.2, ws@0.8.0)
> └── socket.io-client@1.3.7 (to-array@0.1.3, indexof@0.0.1, component-bind@1.0.0, debug@0.7.4, object-component@0.0.3, backo2@1.0.2, component-emitter@1.1.2, has-binary@0.1.6, parseuri@0.0.2, engine.io-client@1.5.4)

nodejs server.js     

> 
> module.js:340
>     throw err;
>     ^
> Error: Cannot find module 'morgan'
>     at Function.Module._resolveFilename (module.js:338:15)
>     at Function.Module._load (module.js:280:25)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/home/mousesport/p2pool-new/nodejs_p2pool_scanner/server.js:7:15)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Function.Module.runMain (module.js:497:10)
> mousesport@1c-server-ucsuc:~/p2pool-new/nodejs_p2pool_scanner$ npm install morgan
> npm http GET https://registry.npmjs.org/morgan
> npm http 304 https://registry.npmjs.org/morgan
> npm http GET https://registry.npmjs.org/depd/0.4.5
> npm http GET https://registry.npmjs.org/on-finished/2.1.0
> npm http GET https://registry.npmjs.org/basic-auth/1.0.0
> npm http 304 https://registry.npmjs.org/basic-auth/1.0.0
> npm http 304 https://registry.npmjs.org/depd/0.4.5
> npm http 304 https://registry.npmjs.org/on-finished/2.1.0
> npm http GET https://registry.npmjs.org/ee-first/1.0.5
> npm http 304 https://registry.npmjs.org/ee-first/1.0.5
> morgan@1.3.2 node_modules/morgan
> ├── basic-auth@1.0.0
> ├── depd@0.4.5
> └── on-finished@2.1.0 (ee-first@1.0.5)

nodejs server.js     

> module.js:340
>     throw err;
>     ^
> Error: Cannot find module 'body-parser'
>     at Function.Module._resolveFilename (module.js:338:15)
>     at Function.Module._load (module.js:280:25)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/home/mousesport/p2pool-new/nodejs_p2pool_scanner/server.js:8:19)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Function.Module.runMain (module.js:497:10)
> mousesport@1c-server-ucsuc:~/p2pool-new/nodejs_p2pool_scanner$ npm install body-parser
> npm http GET https://registry.npmjs.org/body-parser
> npm http 200 https://registry.npmjs.org/body-parser
> npm http GET https://registry.npmjs.org/depd/0.4.5
> npm http GET https://registry.npmjs.org/on-finished/2.1.0
> npm http GET https://registry.npmjs.org/bytes/1.0.0
> npm http GET https://registry.npmjs.org/raw-body/1.3.0
> npm http GET https://registry.npmjs.org/type-is
> npm http GET https://registry.npmjs.org/media-typer/0.3.0
> npm http GET https://registry.npmjs.org/iconv-lite/0.4.4
> npm http GET https://registry.npmjs.org/qs/2.2.4
> npm http 304 https://registry.npmjs.org/on-finished/2.1.0
> npm http 304 https://registry.npmjs.org/depd/0.4.5
> npm http 304 https://registry.npmjs.org/type-is
> npm http 304 https://registry.npmjs.org/raw-body/1.3.0
> npm http 304 https://registry.npmjs.org/bytes/1.0.0
> npm http 304 https://registry.npmjs.org/media-typer/0.3.0
> npm http 304 https://registry.npmjs.org/iconv-lite/0.4.4
> npm http 304 https://registry.npmjs.org/qs/2.2.4
> npm http GET https://registry.npmjs.org/ee-first/1.0.5
> npm http GET https://registry.npmjs.org/mime-types
> npm http 304 https://registry.npmjs.org/ee-first/1.0.5
> npm http 304 https://registry.npmjs.org/mime-types
> npm http GET https://registry.npmjs.org/mime-db
> npm http 304 https://registry.npmjs.org/mime-db
> body-parser@1.8.4 node_modules/body-parser
> ├── raw-body@1.3.0
> ├── media-typer@0.3.0
> ├── bytes@1.0.0
> ├── depd@0.4.5
> ├── qs@2.2.4
> ├── iconv-lite@0.4.4
> ├── on-finished@2.1.0 (ee-first@1.0.5)
> └── type-is@1.5.7 (mime-types@2.0.14)

nodejs server.js       

> Express server listening on port 3000
> GET / 500 14.887 ms - 1042
> Error: Cannot find module 'jade'
>     at Function.Module._resolveFilename (module.js:338:15)
>     at Function.Module._load (module.js:280:25)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at new View (/home/mousesport/p2pool-new/nodejs_p2pool_scanner/node_modules/express/lib/view.js:43:49)
>     at Function.app.render (/home/mousesport/p2pool-new/nodejs_p2pool_scanner/node_modules/express/lib/application.js:509:12)
>     at ServerResponse.res.render (/home/mousesport/p2pool-new/nodejs_p2pool_scanner/node_modules/express/lib/response.js:900:7)
>     at io.on.exec (/home/mousesport/p2pool-new/nodejs_p2pool_scanner/server.js:51:6)
>     at Layer.handle_error (/home/mousesport/p2pool-new/nodejs_p2pool_scanner/node_modules/express/lib/router/layer.js:58:5)
>     at trim_prefix (/home/mousesport/p2pool-new/nodejs_p2pool_scanner/node_modules/express/lib/router/index.js:268:13)

npm install jade

> npm http GET https://registry.npmjs.org/jade
> npm http 304 https://registry.npmjs.org/jade
> npm WARN deprecated jade@1.6.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
> npm http GET https://registry.npmjs.org/constantinople
> npm http GET https://registry.npmjs.org/character-parser/1.2.0
> npm http GET https://registry.npmjs.org/monocle/1.1.51
> npm http GET https://registry.npmjs.org/transformers/2.1.0
> npm http GET https://registry.npmjs.org/void-elements
> npm http GET https://registry.npmjs.org/commander/2.1.0
> npm http GET https://registry.npmjs.org/with
> npm http GET https://registry.npmjs.org/mkdirp
> npm http 304 https://registry.npmjs.org/constantinople
> npm http 304 https://registry.npmjs.org/void-elements
> npm http 304 https://registry.npmjs.org/with
> npm http 200 https://registry.npmjs.org/mkdirp
> npm http 200 https://registry.npmjs.org/commander/2.1.0
> npm http GET https://registry.npmjs.org/commander/-/commander-2.1.0.tgz
> npm http 304 https://registry.npmjs.org/monocle/1.1.51
> npm http 304 https://registry.npmjs.org/transformers/2.1.0
> npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
> npm http 304 https://registry.npmjs.org/character-parser/1.2.0
> npm http 200 https://registry.npmjs.org/commander/-/commander-2.1.0.tgz
> npm http GET https://registry.npmjs.org/readdirp
> npm http GET https://registry.npmjs.org/promise
> npm http GET https://registry.npmjs.org/uglify-js
> npm http GET https://registry.npmjs.org/uglify-js
> npm http GET https://registry.npmjs.org/uglify-js
> npm http GET https://registry.npmjs.org/css
> npm http GET https://registry.npmjs.org/minimist/0.0.8
> npm http 304 https://registry.npmjs.org/readdirp
> npm http 304 https://registry.npmjs.org/uglify-js
> npm http 304 https://registry.npmjs.org/promise
> npm http 200 https://registry.npmjs.org/minimist/0.0.8
> npm http GET https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz
> npm http 304 https://registry.npmjs.org/uglify-js
> npm http 200 https://registry.npmjs.org/css
> npm http 304 https://registry.npmjs.org/uglify-js
> npm http GET https://registry.npmjs.org/is-promise
> npm http GET https://registry.npmjs.org/css-parse/1.0.4
> npm http GET https://registry.npmjs.org/css-stringify/1.0.5
> npm http 200 https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz
> npm http GET https://registry.npmjs.org/source-map
> npm http GET https://registry.npmjs.org/optimist
> npm http 304 https://registry.npmjs.org/is-promise
> npm http GET https://registry.npmjs.org/source-map/0.1.34
> npm http GET https://registry.npmjs.org/async
> npm http GET https://registry.npmjs.org/uglify-to-browserify
> npm http GET https://registry.npmjs.org/yargs
> npm http GET https://registry.npmjs.org/minimatch
> npm http 304 https://registry.npmjs.org/optimist
> npm http 304 https://registry.npmjs.org/async
> npm http 304 https://registry.npmjs.org/uglify-to-browserify
> npm http 304 https://registry.npmjs.org/source-map
> npm http 304 https://registry.npmjs.org/yargs
> npm http 304 https://registry.npmjs.org/css-parse/1.0.4
> npm http 304 https://registry.npmjs.org/minimatch
> npm http 304 https://registry.npmjs.org/css-stringify/1.0.5
> npm http GET https://registry.npmjs.org/brace-expansion
> npm http GET https://registry.npmjs.org/wordwrap
> npm http GET https://registry.npmjs.org/amdefine
> npm http 304 https://registry.npmjs.org/source-map/0.1.34
> npm http 304 https://registry.npmjs.org/brace-expansion
> npm http 304 https://registry.npmjs.org/wordwrap
> npm http 304 https://registry.npmjs.org/amdefine
> npm http GET https://registry.npmjs.org/balanced-match
> npm http GET https://registry.npmjs.org/concat-map/0.0.1
> npm http GET https://registry.npmjs.org/camelcase
> npm http GET https://registry.npmjs.org/wordwrap/0.0.2
> npm http GET https://registry.npmjs.org/decamelize
> npm http GET https://registry.npmjs.org/window-size/0.1.0
> npm http 304 https://registry.npmjs.org/wordwrap/0.0.2
> npm http 304 https://registry.npmjs.org/camelcase
> npm http 304 https://registry.npmjs.org/concat-map/0.0.1
> npm http 304 https://registry.npmjs.org/balanced-match
> npm http 304 https://registry.npmjs.org/decamelize
> npm http 304 https://registry.npmjs.org/window-size/0.1.0
> jade@1.6.0 node_modules/jade
> ├── character-parser@1.2.0
> ├── commander@2.1.0
> ├── void-elements@1.0.0
> ├── mkdirp@0.5.1 (minimist@0.0.8)
> ├── transformers@2.1.0 (promise@2.0.0, css@1.0.8, uglify-js@2.2.5)
> ├── monocle@1.1.51 (readdirp@0.2.5)
> ├── constantinople@2.0.1 (uglify-js@2.4.24)
> └── with@3.0.1 (uglify-js@2.4.24)

nodejs server.js 

> Express server listening on port 3000
> GET / 200 542.997 ms - 7302
> 
> undefined:0
> 
> ^
> SyntaxError: Unexpected end of input
>     at Object.parse (native)
>     at /home/mousesport/p2pool-new/nodejs_p2pool_scanner/server.js:60:51
>     at ChildProcess.exithandler (child_process.js:641:7)
>     at ChildProcess.EventEmitter.emit (events.js:98:17)
>     at maybeClose (child_process.js:743:16)
>     at Socket.<anonymous> (child_process.js:956:11)
>     at Socket.EventEmitter.emit (events.js:95:17)
>     at Pipe.close (net.js:466:12)

**Comment by mousesport** [comment]
nodejs -v
v0.10.25

**Comment by Crahl** [comment]
Readme added with instructions.

**Comment by mousesport** [comment]
```
mousesport@ucsuc:~/p2pool-new/nodejs_p2pool_scanner$ npm install
npm http GET https://registry.npmjs.org/serve-favicon
npm http GET https://registry.npmjs.org/morgan
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/jade
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/moment
npm http GET https://registry.npmjs.org/body-parser
npm http GET https://registry.npmjs.org/socket.io-client
npm http GET https://registry.npmjs.org/socket.io
npm http 304 https://registry.npmjs.org/serve-favicon
npm http 304 https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/morgan
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/socket.io-client
npm http 304 https://registry.npmjs.org/moment
npm http 304 https://registry.npmjs.org/body-parser
npm ERR! Error: No compatible version found: socket.io-client@'file:socket.io'
npm ERR! Valid install targets:
npm ERR! ["0.7.0","0.7.1","0.7.2","0.7.3","0.7.4","0.7.5","0.7.9","0.7.10","0.7.11","0.8.0","0.8.1","0.8.2","0.8.3","0.8.4","0.8.5","0.8.6","0.8.7","0.9.0","0.9.1","0.9.1-1","0.9.2","0.9.3","0.9.4","0.9.5","0.9.6","0.9.7","0.9.8","0.9.9","0.9.10","0.9.11","0.9.15","0.9.16","1.0.0-pre","1.0.0-pre2","1.0.0-pre3","1.0.0-pre4","1.0.0-pre5","0.9.17","1.0.1","1.0.2","1.0.3","1.0.4","1.0.5","1.0.6","1.1.0","1.2.0","1.2.1","1.3.0","1.3.1","1.3.2","1.3.3","1.3.4","1.3.5","1.3.6","1.3.7","1.4.0","1.4.1","1.4.2","1.4.3","1.4.4","1.4.5","1.4.6","1.4.7","1.4.8","1.5.0","1.5.1","1.6.0","1.7.0","1.7.1","1.7.2","1.7.3","1.7.4","2.0.0","2.0.1"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.19.0-25-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/mousesport/p2pool-new/nodejs_p2pool_scanner
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm http 304 https://registry.npmjs.org/socket.io
npm http 304 https://registry.npmjs.org/jade
npm WARN deprecated jade@1.6.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/mousesport/p2pool-new/nodejs_p2pool_scanner/npm-debug.log
npm ERR! not ok code 0
```
